{% set name = "spyder-reports" %}
{% set import = "spyder_reports" %}
{% set version = "0.1.1" %}
{% set sha256 = "30362a96aa1d0eb9e8f09fd3fbfa3b07255e1cf656a80be2b95ee3ae85a0d504" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1003
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >=3.5
    - spyder >=3.2
    - pweave
    - qtpy
    - pandoc
    - matplotlib

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    # - {{ import }}  # Fails to import on current CF due to too-new Python ver

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Spyder-IDE plugin for Markdown reports using Pweave.'
  description: |
    Currently it supports basic functionality such as rendering mdw and md reports,
    and saving them in your filesystem.
  dev_url: https://github.com/spyder-ide/spyder-reports
  doc_url: https://github.com/spyder-ide/spyder-reports

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - ccordoba12
