# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jALpvs5I6QdoG2kcMhIQkkAWUCpDSjQh/gNA+k1xk8pJtZ2i+MBiIdCPJqt9OxVvojuiGzafrL7PVywRrH4YHDoMTamLJQcEWHqQ32WXNld3ufXDp4i/vCCebZYCX4XMSRW7jNPfYudKPuw6jrOY+ywhQ3RnvNvlDyFA0VaARf+ez/v+seOZtZubk8WVDJNzfaOPK+CY5mC8y9JK/QD5UpmmC+B+I6NBq65vlHghkioTGdxYvKqNjlJ3DpaWg0Wkw/HnmAqGIWa01iRPgmM+9CF+EEZ0fb2dckE1DZZH84W+S1k9yFxGDoSUG7IJfo0hwPhfBuAaxzH0M2Bh9h9hVvmOGdVgv0FHyWBssT1O9Mgsiq7WmQeoF6527z6w6ScbLhDPC5++efNDgff+i9UwQUl/6zPO+QyYBN55qTM6vQMMWfR9WldKPzMDk+c4Vg+w+/ZQNHklLi1q5VkZno/hwHH+Ya6OUNETh/hGBD1ho+Om7ojbMYvFXzHbYGhv6VVPGB5nNVC/lWEATrw63WXVfdE/7PB5Gj68JzRGW1f9AdfRC50zI01lKH1oHNqx6S4xN71Dk1B9eezR56P1mTeyf8VBmGjkHjZzR3ap1ZbqAvtTMDBZICEpKUpkuDQUcn5p58/cAo7XsgZEsNVLdRdNM2MO4o6KB76jnKUfFHJbIAw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
