appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jALpvs5I6QdoG2kcMhIQkkAWUCpDSjQh/gNA+k1xk8pJtZ2i+MBiIdCPJqt9OxVvojuiGzafrL7PVywRrH4YHDoMTamLJQcEWHqQ32WXNld3ufXDp4i/vCCebZYCX4XMSRW7jNPfYudKPuw6jrOY+ywhQ3RnvNvlDyFA0VaARf+ez/v+seOZtZubk8WVDJNzfaOPK+CY5mC8y9JK/QD5UpmmC+B+I6NBq65vlHghkioTGdxYvKqNjlJ3DpaWg0Wkw/HnmAqGIWa01iRPgmM+9CF+EEZ0fb2dckE1DZZH84W+S1k9yFxGDoSUG7IJfo0hwPhfBuAaxzH0M2Bh9h9hVvmOGdVgv0FHyWBssT1O9Mgsiq7WmQeoF6527z6w6ScbLhDPC5++efNDgff+i9UwQUl/6zPO+QyYBN55qTM6vQMMWfR9WldKPzMDk+c4Vg+w+/ZQNHklLi1q5VkZno/hwHH+Ya6OUNETh/hGBD1ho+Om7ojbMYvFXzHbYGhv6VVPGB5nNVC/lWEATrw63WXVfdE/7PB5Gj68JzRGW1f9AdfRC50zI01lKH1oHNqx6S4xN71Dk1B9eezR56P1mTeyf8VBmGjkHjZzR3ap1ZbqAvtTMDBZICEpKUpkuDQUcn5p58/cAo7XsgZEsNVLdRdNM2MO4o6KB76jnKUfFHJbIAw=}
conda_forge_output_validation: false
